/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

// ── Session axis (per-conversation) ────────────────────────────────
export {
  DaemonSessionProvider,
  useDaemonActions,
  useDaemonActiveTodoList,
  useDaemonConnection,
  useDaemonPendingPermissions,
  useDaemonPromptStatus,
  useDaemonSessionNotices,
  useDaemonSessionOwnerGuard,
  useDaemonStreamingState,
  useDaemonSession,
  useDaemonTranscriptBlocks,
  useDaemonTranscriptHistory,
  useDaemonTranscriptState,
  useDaemonTranscriptStore,
  useDaemonTurnNavigationState,
  useDaemonTurnNavigationStore,
  useDaemonWorkspaceEventSignals,
  extractDaemonTodosFromToolBlock,
  hasDaemonActiveTodos,
  isDaemonSubAgentToolBlock,
  parseDaemonTodoItemsFromEntries,
  selectDaemonActiveTodoList,
  selectDaemonLatestTodoList,
  selectDaemonPendingPermissions,
  selectDaemonSubAgentToolBlocks,
  selectDaemonStreamingState,
  selectDaemonTodoLists,
  selectDaemonTranscriptStreamingState,
  isMissingSessionHttpStatus,
  toDaemonPromptContent,
} from './session/index.js';
export type {
  DaemonCommandInfo,
  DaemonConnectionState,
  DaemonConnectionStatus,
  DaemonModelInfo,
  DaemonProductSessionContext,
  DaemonStandaloneConnectionState,
  DaemonNoticeCategory,
  DaemonNoticeOperation,
  DaemonNoticeSeverity,
  DaemonPromptFile,
  DaemonPromptImage,
  DaemonPromptStatus,
  DaemonReasoningControls,
  DaemonSessionActions,
  DaemonSessionContextValue,
  DaemonSessionNotice,
  DaemonSessionOwnerGuard,
  DaemonSessionOwnerSnapshot,
  DaemonSessionProviderProps,
  DaemonTranscriptHistory,
  DaemonPromptAdmission,
  DaemonProvisionalTurn,
  DaemonSelectedTurnState,
  DaemonTurnIndexPage,
  DaemonTurnLocation,
  DaemonTurnNavigationClient,
  DaemonTurnNavigationError,
  DaemonTurnNavigationSession,
  DaemonTurnNavigationSnapshot,
  DaemonTurnNavigationStore,
  HistoricalTranscriptPage,
  HistoricalTranscriptRange,
  TranscriptBoundary,
  DaemonTokenUsage,
  DaemonTodoItem,
  DaemonTodoList,
  DaemonTodoPriority,
  DaemonTodoStatus,
  DaemonStreamingState,
  DaemonWorkspaceEventSignals,
  PendingPromptActionOptions,
  SendPromptOptions,
  SubmitPromptOptions,
  SubmitPromptResult,
} from './session/index.js';

// ── Workspace axis (per-workspace, outlives sessions) ──────────────
export {
  DaemonWorkspaceProvider,
  useDaemonWorkspace,
  useDaemonWorkspaceActions,
  useOptionalDaemonWorkspace,
  useDaemonAgents,
  useDaemonAuth,
  useDaemonChannels,
  useDaemonDiagnostics,
  useDaemonFiles,
  useDaemonGlob,
  useDaemonMcp,
  useDaemonMemory,
  useDaemonResource,
  useDaemonSessions,
  useDaemonSkills,
  useDaemonStatusReport,
  useDaemonUsageDashboard,
  useDaemonTools,
  useDaemonSettings,
  useDaemonProviders,
} from './workspace/index.js';
export type {
  DaemonDirectoryEntry,
  DaemonDirectoryListing,
  DaemonFileStat,
  DaemonGlobOptions,
  DaemonGlobResult,
  DaemonGoal,
  DaemonGoalList,
  DaemonScheduledTask,
  DaemonScheduledTaskRun,
  DaemonCreateScheduledTaskRequest,
  DaemonUpdateScheduledTaskRequest,
  DaemonResourceOptions,
  DaemonChannelPairingActions,
  DaemonChannelsResource,
  DaemonStatusReportOptions,
  DaemonUsageDashboardOptions,
  DaemonWorkspaceActions,
  DaemonWorkspaceContextValue,
  DaemonWorkspaceProviderProps,
  DaemonWorkspaceStatus,
  ResourceResult,
  ResourceState,
} from './workspace/index.js';

export {
  useDaemonFollowupSuggestion,
  type UseDaemonFollowupSuggestionReturn,
} from './useDaemonFollowupSuggestion.js';

export { useDaemonMidTurnInjected } from './useDaemonMidTurnInjected.js';

export {
  getPendingPromptVersion,
  getPendingPromptEvents,
  consumePendingPromptEvents,
  subscribePendingPromptEvents,
  subscribePendingPromptVersion,
} from './pendingPromptVersion.js';

// ── Re-exported SDK types/constants for UI consumers ──────────────
// These allow web-shell and other UI packages to depend only on
// @qwen-code/web-shell without importing @qwen-code/sdk/daemon directly.
export { DAEMON_APPROVAL_MODES } from '@qwen-code/sdk/daemon';
export type {
  DaemonApprovalMode,
  DaemonAuthProviderBaseUrlOption,
  DaemonAuthProviderCatalog,
  DaemonAuthProviderDescriptor,
  DaemonAuthProviderInstallRequest,
  DaemonAuthProviderInstallResult,
  DaemonModelProviderRuntimeSyncResult,
  DaemonAuthProviderModel,
  DaemonContextCategoryBreakdown,
  DaemonContextFileScope,
  DaemonContextMemoryDetail,
  DaemonContextSkillDetail,
  DaemonContextToolDetail,
  DaemonSessionContextUsage,
  DaemonSessionContextUsageStatus,
  DaemonSessionStatsModelMetrics,
  DaemonSessionStatsSource,
  DaemonSessionStatsStatus,
  DaemonSessionStatsToolByName,
  DaemonSessionSummary,
  DaemonUsageRange,
  DaemonUsageDashboard,
  DaemonUsageDashboardTotals,
  DaemonUsageModelShare,
  DaemonUsageSkillCall,
  DaemonUsageDailyPoint,
  DaemonUsageHeatmapDay,
  DaemonStatusReport,
  DaemonStatusReportDetail,
  DaemonStatusReportIssue,
  DaemonStatusReportLevel,
  DaemonStatusReportSection,
  DaemonStatusReportSession,
  DaemonMetricsSeriesBucket,
  DaemonWorkspaceAgentDetail,
  DaemonWorkspaceAgentSummary,
  DaemonWorkspaceGenerationEvent,
  DaemonWorkspaceMcpServerStatus,
  DaemonWorkspaceMcpToolStatus,
  DaemonWorkspaceMcpToolsStatus,
  DaemonWorkspaceMcpResourceStatus,
  DaemonWorkspaceMcpResourcesStatus,
  DaemonWorkspaceMemoryFile,
  DaemonWorkspaceSkillStatus,
  DaemonWorkspaceToolStatus,
  DaemonSettingDescriptor,
  DaemonWorkspaceSettingsStatus,
  DaemonSettingUpdateResult,
  DaemonWorkspaceProvidersStatus,
  DaemonWorkspaceProviderStatus,
  DaemonWorkspaceProviderModel,
  DaemonWorkspaceProviderCurrent,
  DaemonChannelConfigFieldKind,
  DaemonChannelConfigFieldDescriptor,
  DaemonChannelConfigValueFieldDescriptor,
  DaemonChannelConfigPlainValueFieldDescriptor,
  DaemonChannelConfigEnumFieldDescriptor,
  DaemonChannelConfigNumberFieldDescriptor,
  DaemonChannelConfigObjectFieldDescriptor,
  DaemonChannelConfigNestedFieldDescriptor,
  DaemonChannelTypeDescriptor,
  DaemonChannelTypeCatalog,
  DaemonChannelRuntimeState,
  DaemonChannelSecretState,
  DaemonChannelInstanceSnapshot,
  DaemonChannelsSnapshot,
  DaemonChannelSecretUpdate,
  DaemonRevisionRequest,
  DaemonChannelUpsertRequest,
  DaemonChannelStartupRequest,
  DaemonChannelMutationResult,
  DaemonChannelPairingRequest,
  DaemonChannelPairingSubject,
  DaemonChannelPairingRequestsSnapshot,
  DaemonChannelPairingApprovalRequest,
  DaemonChannelPairingApprovalResult,
  DaemonChannelPairingApprovalsSnapshot,
  DaemonChannelPairingRevocationRequest,
  DaemonChannelPairingRevocationResult,
  DaemonModelDeleteRequest,
  DaemonModelDeleteResult,
} from '@qwen-code/sdk/daemon';
